name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build with Maven
        run: mvn -B package --file ./querifybackend/pom.xml

      - name: Run Tests
        run: mvn test --file ./querifybackend/pom.xml
